eshop/accounts/urls.py
from django.urls import path,include
from django.conf.urls import url
from django.contrib.auth.views import LogoutView
from .views import *
# from referrals import urls

app_name = 'accounts'
urlpatterns = [
    # authentication section
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/guest', guest_register_view, name='guest_register'),
    # url(r'^referrals/', include('referrals.urls', namespace='referrals')),
]

eshop/carts/urls.py
from django.urls import path,re_path
from .views import *

app_name = 'cart'

urlpatterns = [

    path('', cart_home,name='home'),
    path('checkout/', checkout_home,name='checkout'),
    path('update/', cart_update,name='update'),
    path('checkout/succcess/', checkout_done,name='success'),

]

eshop/eshop/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,re_path, include

from address.views import checkout_address_created_view,checkout_address_reuse_view
from .views import *
from carts.views import cart_detail_api_view
from billing.views import pyment_method_view, payment_method_creat_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('about/', about_page, name='about'),

    # including products app
    path('', include('products.urls')),

    # including login apps
    path('', include('accounts.urls')),

    # including search app
    path('search/', include('search.urls')),

    # including carts app
    path('cart/', include('carts.urls')),
    path('api/cart/', cart_detail_api_view, name='api-cart'),

    # authentication section
    path('contact/', contact_page, name='contact'),

    # mapping address view
    path('checkout_address_created_view/', checkout_address_created_view, name='checkout_address_created'),
    path('checkout/address/reuse/view/', checkout_address_reuse_view, name='checkout_address_reuse'),

    # payments
    path('payments/methods/', pyment_method_view, name='payment-method'),
    path('payments/methods/create/', payment_method_creat_view, name='payment-method-api'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/carts/models.py
import math
from django.db import models
from django.conf import settings
from products.models import Product
from django.db.models.signals import m2m_changed, pre_save
# Create your models here.

User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):

    # creating cart object on model so that we can use it where ever we neeed
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)

    # if the id is exits than go else create one
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            # if there is some issue than it's might me ( cart_obj = self.new_cart(user=request.user) )
            cart_obj = Cart.objects.new_cart(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id

        return cart_obj, new_obj
    def new_cart(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, decimal_places=2, max_digits=100)
    total       = models.DecimalField(default=0.0, decimal_places=2, max_digits=100)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

"""
using m2m signal we are managing calcultion of cart.
"""


# creating signal so that we can calculate our products at the time of shopping
def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    products = instance.products.all()
    total = 0
    for x in products:
        total += x.price
    if instance.subtotal != total:
        instance.subtotal = total
        instance.save()
m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

# calculating subtotal like delevary cost etc .....
def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    instance.total = math.fsum([instance.subtotal,1.8])

pre_save.connect(pre_save_cart_receiver, sender=Cart)

eshop/carts/views.py
import stripe
from django.conf import settings
from django.shortcuts import redirect, render
from django.http import JsonResponse
from accounts.forms import GuestForm, LoginForm
from accounts.models import GuestEmail
from address.forms import AddressForm
from address.models import Address
from billing.models import BillingProfile
from orders.models import Order
from products.models import Product
from .models import Cart

# Create your views here.

# method for create a cart for user.

STRIPE_SEC_KEY = getattr(settings, "STRIPE_SEC_KEY")
stripe.api_key = STRIPE_SEC_KEY
STRIPE_PUB_KEY = getattr(settings, "STRIPE_PUB_KEY")

def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products    = [
        {
            "title":x.title,
            "price":x.price,
            "url":x.get_absolute_url(),
            "id":x.id,
            "slug":x.slug
        } for x in cart_obj.products.all()]

    # products_list = []
    # for x in cart_obj.products.all():
    #     products_list.append({"title:":x.title, "price":x.price})

    cart_data   = {"products": products, "subtotal": cart_obj.subtotal, "total": cart_obj.total}
    return  JsonResponse(cart_data)


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    context = {
        "cart" : cart_obj,
    }
    return render(request, 'carts/cart_home.html', context)


# Update view for cart
def cart_update(request):
    # getting the product_id which is sent from the update_cart.html
    product_id  = request.POST.get('product_id')

    # if the product_id is not none then we taking it to product_obj
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except DoesNotExist:
            return redirect("cart:home")   # if product is not exists simply just redirect to home
        cart_obj, new_obj = Cart.objects.new_or_get(request)    # we also added this line to products view on get_context_data so that we can add cart to specific product

        # if the product_obj is exists in cart than we can remove
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            data_added = False
        # if the product_obj is exists in cart than we can add it
        else:
            cart_obj.products.add(product_obj)
            data_added = True

        # return redirect(product_obj.get_absolute_url())
        request.session['total_product'] = cart_obj.products.count()

        if request.is_ajax():
            print("Ajax request")
            json_data = {
                'added'     : data_added,
                'removed'   : not data_added,
                'itemCount' : cart_obj.products.count(),
            }
            return  JsonResponse(json_data)
    return redirect("cart:home")


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect('cart:home')

    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)

    if not request.user.is_authenticated:
        billing_profile = None

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    has_card = False
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]

        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            del request.session["billing_address_id"]

        if billing_address_id or shipping_address_id:
            order_obj.save()

        has_card = billing_profile.has_card

    if request.method == "POST":
        "check the cart process done"
        is_prepared = order_obj.check_done()
        if is_prepared:
            did_chared, crg_msg = billing_profile.charge(order_obj)
            if did_chared:
                order_obj.mark_paid()
                request.session['total_product'] = 0
                del request.session['cart_id']
                if not billing_profile.user:
                    billing_profile.set_card_inactive()
                return redirect("cart:success")
            else:
                print(crg_msg)
                return redirect("cart:checkout")
    context = {
        'object': order_obj,
        'billing_profile' : billing_profile,
        'login_form' : login_form,
        'guest_form' : guest_form,
        'address_form' : address_form,
        'address_qs' : address_qs,
        "has_card": has_card,
        "publish_key": STRIPE_PUB_KEY
    }
    return render(request, 'carts/checkout.html', context)


def checkout_done(request):
    return render(request, 'carts/checkout-done.html',{})

eshop/carts/templates/carts/cart_home.html
{% extends 'base.html'%}

{% block content%}
    <h2>Cart</h2>
    {% if cart.products.exists %}
        <table class="table table-striped cart-table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Product Price</th>
              </tr>
            </thead>

            <tbody class="cart-table-body">
            {% for product in cart.products.all %}
              <tr class="cart-product">
                <th scope="row">{{forloop.counter}}</th>
                <td>
                  <a href="{{product.get_absolute_url}}">{{product.title}}</a>
                  {% include 'carts/snippets/remove-product.html' with product_id=product.id %}
                </td>
                <td>{{product.price}}</td>
              </tr>
            {%endfor%}
              <tr>
                <td colspan="2"></td>
                  <td><b>Subtotal </b>$<span class="cart-subtotal">{{cart.subtotal}}</span></td>
              </tr>
              <tr>
                <td colspan="2"></td>
                <td><b>Total </b>$ <span class="cart-total">{{cart.total}}</span></td>
              </tr>
              <tr>
                <td colspan="2"></td>
                <td><a class="btn btn-info" href="{% url 'cart:checkout' %}">checkout</a></td>
              </tr>
            </tbody>
        </table>
    <div class="remove-product-item" style="display: none;">
        {% include 'carts/snippets/remove-product.html' %}
    </div>
    {%else%}
        <p class="lead">Cart empty</p>
    {%endif%}
{%endblock%}

eshop/carts/templates/carts/checkout-done.html
{% extends 'base.html'%}

{% block content%}
    <div class="col-6 mx-auto py-5 text-center">
        <h1 class="display-1">Thank you for order !!!!</h1>
    </div>
{%endblock%}

eshop/carts/templates/carts/checkout.html
{% extends 'base.html' %}
{% block content %}
    {{ object.order_id }} -- {{ object.cart }}
    {% if not billing_profile %}
        <div class="row text-center">
            <div class="col-12 col-md-6">
                <p class="lead">Login</p>
                {% include 'snippets/login.html' with form=login_form next_uri=request.build_absolute_uri %}
            </div>
            <div class="col-12 col-md-6">
                <p class="lead">Continue as guest</p>
                {% url 'accounts:guest_register' as guest_register_url %}
                {% include 'snippets/login.html' with form=guest_form next_uri=request.build_absolute_uri action_url=guest_register_url %}
            </div>
        </div>
    {% else %}
        {% if not object.shipping_address %}

            <div class="row">
                <div class="col-12">
                    <p class="lead">Shipping Address</p>
                    <hr>
                </div>
                <div class="col-6">

                    {% url 'checkout_address_created' as checkout_address_created %}
                    {% include 'address/form.html' with form=address_form next_uri=request.build_absolute_uri action_url=checkout_address_created address_type='shipping' %}

                </div>
                {% if address_qs.exists %}
                    <div class="col-6">
                        {% url "checkout_address_reuse" as checkout_address_reuse %}
                        {% include 'address/previous_address.html' with address_qs=address_qs  next_uri=request.build_absolute_uri action_url=checkout_address_reuse address_type='shipping' %}
                    </div>
                {% endif %}
            </div>


        {% elif not object.billing_address %}

            <div class="row">
                <div class="col-12">
                    <p class="lead">Billing Address</p>
                    <hr>
                </div>
                <div class="col-6">
                    {% url 'checkout_address_created' as checkout_address_created %}
                    {% include 'address/form.html' with form=address_form next_uri=request.build_absolute_uri action_url=checkout_address_created address_type='billing' %}
                </div>
                {% if address_qs.exists %}
                    <div class="col-6">
                        {% url "checkout_address_reuse" as checkout_address_reuse %}
                        {% include 'address/previous_address.html' with address_qs=address_qs  next_uri=request.build_absolute_uri action_url=checkout_address_reuse address_type='billing' %}
                    </div>
                {% endif %}
            </div>

        {% else %}
            {% if not has_card %}
                <div class="col-10 col-md-6 mx-auto">
                    <div class="stripe-payment-form" data-token="{{ publish_key }}"
                         data-next-url='{{ request.build_absolute_uri }}' data-btn-title="Add New button">
                    </div>

                </div>
            {% else %}
                <h2>Finalize Checkout</h2>
                <p>Total product : {{ object.cart.products.all.count }}</p>
                <p>Cart Item: {% for product in object.cart.products.all %}
                    {{ product|upper }}{% if not foorloop.last %}, {% endif %}{% endfor %}</p>
                <p>Shipping Address: {{ object.shipping_address.get_address }}</p>
                <p>Billing Address: {{ object.billing_address.get_address }}</p>
                <p>Cart total: {{ object.cart.total }}</p>
                <p>Shipping toatal: {{ object.shipping_total }}</p>
                <p>Oreder total: {{ object.total }}</p>
                <form class="form" method="POST" action="">{% csrf_token %}
                    <button type="submit" class="btn btn-success">Checkout</button>
                </form>
            {% endif %}
        {% endif %}
    {% endif %}
{% endblock %}